# FM-G-CAM Quantitative Evaluation Configuration ########################################
gpu_device: cuda:0

# Number of classes that CAM should be generated for
class_count: 5

# Image size to be used for evaluation
image_size: 224

# Number of samples to be used for evaluation. If set to -1, all samples will be used
sample_count: 3

# Path to the directory containing the images
data_path: ./example_data/MSCOCO_Sample

# Path to the directory containing the output results
output_path: ./output/
